name: dare
channels:
- conda-forge
dependencies:
- python==3.12
- pip
- numpy
- pandas>=2
- netcdf4
- pypsa>=0.33
- tabula-py
- xlrd
- lxml
- pytables
- pyxlsb
- openpyxl
- libgdal-hdf5
- libgdal-netcdf
- cartopy>=0.22
- matplotlib>=3.6
- plotly<6
- ipython
- jupyterlab
- jupyter-book
- ghp-import
- pre-commit
- pip:
  - highspy>=1.9
